[profile.default]
src = 'src'
out = 'out'
libs = ["../../node_modules", "../../lib"]
remappings = [
    '@chainlink/=node_modules/@chainlink/',
    '@opengsn/=node_modules/@opengsn/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
    'truffle/=node_modules/truffle/',
]

[profile.default.rpc_endpoints]
rinkeby = 'https://rinkeby.infura.io/v3/${INFURA_API_KEY}'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config