packages:
  - "packages/owlprotocol-contracts"
  - "packages/owlprotocol-contracts-docs"
  - "packages/owlprotocol-contract-helpers/opengsn"
  - "packages/owlprotocol-contract-helpers/ipfs-merkletrees"
