packages:
  - "packages/nft-launcher-contracts-lib"
  - "packages/nft-launcher-contracts-sol"
  - "packages/owlprotocol-contracts"
  - "packages/owlprotocol-contracts-docs"
  - "packages/owlprotocol-contract-helpers/opengsn"
  - "packages/owlprotocol-contract-helpers/cloudtrees"
