/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MintGuardLimitedMintsInterface extends ethers.utils.Interface {
  functions: {
    "allowMint(uint256,address)": FunctionFragment;
    "setUserMints(address,uint256,address,uint64)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allowMint",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserMints",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "allowMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUserMints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;

  events: {
    "SetAllowedMints(address,uint256,address,uint64)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SetAllowedMints"): EventFragment;
}

export type SetAllowedMintsEvent = TypedEvent<
  [string, BigNumber, string, BigNumber] & {
    minterContract: string;
    speciesId: BigNumber;
    user: string;
    mintsAllowed: BigNumber;
  }
>;

export class MintGuardLimitedMints extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MintGuardLimitedMintsInterface;

  functions: {
    allowMint(
      speciesId: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUserMints(
      minterContract: string,
      speciesId: BigNumberish,
      user: string,
      mintsAllowed: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  allowMint(
    speciesId: BigNumberish,
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUserMints(
    minterContract: string,
    speciesId: BigNumberish,
    user: string,
    mintsAllowed: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    allowMint(
      speciesId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setUserMints(
      minterContract: string,
      speciesId: BigNumberish,
      user: string,
      mintsAllowed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "SetAllowedMints(address,uint256,address,uint64)"(
      minterContract?: null,
      speciesId?: null,
      user?: null,
      mintsAllowed?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber],
      {
        minterContract: string;
        speciesId: BigNumber;
        user: string;
        mintsAllowed: BigNumber;
      }
    >;

    SetAllowedMints(
      minterContract?: null,
      speciesId?: null,
      user?: null,
      mintsAllowed?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber],
      {
        minterContract: string;
        speciesId: BigNumber;
        user: string;
        mintsAllowed: BigNumber;
      }
    >;
  };

  estimateGas: {
    allowMint(
      speciesId: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUserMints(
      minterContract: string,
      speciesId: BigNumberish,
      user: string,
      mintsAllowed: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allowMint(
      speciesId: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUserMints(
      minterContract: string,
      speciesId: BigNumberish,
      user: string,
      mintsAllowed: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
