/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MintGuardAllowlistInterface extends ethers.utils.Interface {
  functions: {
    "addAllowedUser(address,uint256,address)": FunctionFragment;
    "allowMint(uint256,address)": FunctionFragment;
    "removeAllowedUser(address,uint256,address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addAllowedUser",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "allowMint",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAllowedUser",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAllowedUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAllowedUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;

  events: {
    "AddAllowedUser(address,uint256,address)": EventFragment;
    "RemoveAllowedUser(address,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddAllowedUser"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveAllowedUser"): EventFragment;
}

export type AddAllowedUserEvent = TypedEvent<
  [string, BigNumber, string] & {
    minterContract: string;
    speciesId: BigNumber;
    user: string;
  }
>;

export type RemoveAllowedUserEvent = TypedEvent<
  [string, BigNumber, string] & {
    minterContract: string;
    speciesId: BigNumber;
    user: string;
  }
>;

export class MintGuardAllowlist extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MintGuardAllowlistInterface;

  functions: {
    addAllowedUser(
      minterContract: string,
      speciesId: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    allowMint(
      speciesId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    removeAllowedUser(
      minterContract: string,
      speciesId: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  addAllowedUser(
    minterContract: string,
    speciesId: BigNumberish,
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  allowMint(
    speciesId: BigNumberish,
    user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  removeAllowedUser(
    minterContract: string,
    speciesId: BigNumberish,
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    addAllowedUser(
      minterContract: string,
      speciesId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    allowMint(
      speciesId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeAllowedUser(
      minterContract: string,
      speciesId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "AddAllowedUser(address,uint256,address)"(
      minterContract?: null,
      speciesId?: null,
      user?: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { minterContract: string; speciesId: BigNumber; user: string }
    >;

    AddAllowedUser(
      minterContract?: null,
      speciesId?: null,
      user?: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { minterContract: string; speciesId: BigNumber; user: string }
    >;

    "RemoveAllowedUser(address,uint256,address)"(
      minterContract?: null,
      speciesId?: null,
      user?: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { minterContract: string; speciesId: BigNumber; user: string }
    >;

    RemoveAllowedUser(
      minterContract?: null,
      speciesId?: null,
      user?: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { minterContract: string; speciesId: BigNumber; user: string }
    >;
  };

  estimateGas: {
    addAllowedUser(
      minterContract: string,
      speciesId: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    allowMint(
      speciesId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeAllowedUser(
      minterContract: string,
      speciesId: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addAllowedUser(
      minterContract: string,
      speciesId: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    allowMint(
      speciesId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeAllowedUser(
      minterContract: string,
      speciesId: BigNumberish,
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
