/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type InterfaceImplementerSet = ContractEventLog<{
  addr: string;
  interfaceHash: string;
  implementer: string;
  0: string;
  1: string;
  2: string;
}>;
export type ManagerChanged = ContractEventLog<{
  addr: string;
  newManager: string;
  0: string;
  1: string;
}>;

export interface ERC1820Registry extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ERC1820Registry;
  clone(): ERC1820Registry;
  methods: {
    getInterfaceImplementer(
      _addr: string,
      _interfaceHash: string | number[]
    ): NonPayableTransactionObject<string>;

    getManager(_addr: string): NonPayableTransactionObject<string>;

    implementsERC165Interface(
      _contract: string,
      _interfaceId: string | number[]
    ): NonPayableTransactionObject<boolean>;

    implementsERC165InterfaceNoCache(
      _contract: string,
      _interfaceId: string | number[]
    ): NonPayableTransactionObject<boolean>;

    interfaceHash(_interfaceName: string): NonPayableTransactionObject<string>;

    setInterfaceImplementer(
      _addr: string,
      _interfaceHash: string | number[],
      _implementer: string
    ): NonPayableTransactionObject<void>;

    setManager(
      _addr: string,
      _newManager: string
    ): NonPayableTransactionObject<void>;

    updateERC165Cache(
      _contract: string,
      _interfaceId: string | number[]
    ): NonPayableTransactionObject<void>;
  };
  events: {
    InterfaceImplementerSet(
      cb?: Callback<InterfaceImplementerSet>
    ): EventEmitter;
    InterfaceImplementerSet(
      options?: EventOptions,
      cb?: Callback<InterfaceImplementerSet>
    ): EventEmitter;

    ManagerChanged(cb?: Callback<ManagerChanged>): EventEmitter;
    ManagerChanged(
      options?: EventOptions,
      cb?: Callback<ManagerChanged>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(
    event: "InterfaceImplementerSet",
    cb: Callback<InterfaceImplementerSet>
  ): void;
  once(
    event: "InterfaceImplementerSet",
    options: EventOptions,
    cb: Callback<InterfaceImplementerSet>
  ): void;

  once(event: "ManagerChanged", cb: Callback<ManagerChanged>): void;
  once(
    event: "ManagerChanged",
    options: EventOptions,
    cb: Callback<ManagerChanged>
  ): void;
}
