/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface InterfaceIds extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): InterfaceIds;
  clone(): InterfaceIds;
  methods: {
    minterAutoIdInterfaceId(): NonPayableTransactionObject<string>;

    minterBreedingInterfaceId(): NonPayableTransactionObject<string>;

    minterCoreInterfaceId(): NonPayableTransactionObject<string>;

    minterRandomInterfaceId(): NonPayableTransactionObject<string>;

    minterSimpleInterfaceId(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
