/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type CreateSpecies = ContractEventLog<{
  speciesId: string;
  contractAddr: string;
  owner: string;
  mintFeeToken: string;
  mintFeeAddress: string;
  mintFeeAmount: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
  5: string;
}>;
export type Initialized = ContractEventLog<{
  version: string;
  0: string;
}>;
export type MintSpecies = ContractEventLog<{
  speciesId: string;
  to: string;
  tokenId: string;
  parents: string[];
  0: string;
  1: string;
  2: string;
  3: string[];
}>;
export type SetBreedingRules = ContractEventLog<{
  speciesId: string;
  requiredParents: string;
  breedCooldownSeconds: string;
  genes: string[];
  mutationRates: string[];
  0: string;
  1: string;
  2: string;
  3: string[];
  4: string[];
}>;

export interface MinterBreeding extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): MinterBreeding;
  clone(): MinterBreeding;
  methods: {
    breed(
      speciesId: number | string | BN,
      parents: (number | string | BN)[]
    ): NonPayableTransactionObject<string>;

    canImplementInterfaceForAddress(
      interfaceHash: string | number[],
      arg1: string
    ): NonPayableTransactionObject<string>;

    createSpecies(
      contractAddress: string,
      mintFeeToken: string,
      mintFeeAddress: string,
      mintFeeAmount: number | string | BN
    ): NonPayableTransactionObject<void>;

    defaultBreedingCooldownSeconds(): NonPayableTransactionObject<string>;

    defaultGenesNum(): NonPayableTransactionObject<string>;

    defaultRequiredParents(): NonPayableTransactionObject<string>;

    getBreedingRules(
      speciesId: number | string | BN
    ): NonPayableTransactionObject<{
      requiredParents: string;
      breedCooldownSeconds: string;
      genes: string[];
      mutationRates: string[];
      0: string;
      1: string;
      2: string[];
      3: string[];
    }>;

    getSpecies(speciesId: number | string | BN): NonPayableTransactionObject<{
      contractAddr: string;
      owner: string;
      mintFeeToken: string;
      mintFeeAmount: string;
      mintFeeAddress: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
    }>;

    initialize(): NonPayableTransactionObject<void>;

    safeBreed(
      speciesId: number | string | BN,
      parents: (number | string | BN)[]
    ): NonPayableTransactionObject<string>;

    setBreedingRules(
      speciesId: number | string | BN,
      requiredParents: number | string | BN,
      generationCooldownMultiplier: number | string | BN,
      breedCooldownSeconds: number | string | BN,
      genes: (number | string | BN)[],
      mutationRates: (number | string | BN)[]
    ): NonPayableTransactionObject<string>;

    setMintGuard(
      speciesId: number | string | BN,
      mintGuardAddress: string
    ): NonPayableTransactionObject<void>;

    supportsInterface(
      interfaceId: string | number[]
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    CreateSpecies(cb?: Callback<CreateSpecies>): EventEmitter;
    CreateSpecies(
      options?: EventOptions,
      cb?: Callback<CreateSpecies>
    ): EventEmitter;

    Initialized(cb?: Callback<Initialized>): EventEmitter;
    Initialized(
      options?: EventOptions,
      cb?: Callback<Initialized>
    ): EventEmitter;

    MintSpecies(cb?: Callback<MintSpecies>): EventEmitter;
    MintSpecies(
      options?: EventOptions,
      cb?: Callback<MintSpecies>
    ): EventEmitter;

    SetBreedingRules(cb?: Callback<SetBreedingRules>): EventEmitter;
    SetBreedingRules(
      options?: EventOptions,
      cb?: Callback<SetBreedingRules>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "CreateSpecies", cb: Callback<CreateSpecies>): void;
  once(
    event: "CreateSpecies",
    options: EventOptions,
    cb: Callback<CreateSpecies>
  ): void;

  once(event: "Initialized", cb: Callback<Initialized>): void;
  once(
    event: "Initialized",
    options: EventOptions,
    cb: Callback<Initialized>
  ): void;

  once(event: "MintSpecies", cb: Callback<MintSpecies>): void;
  once(
    event: "MintSpecies",
    options: EventOptions,
    cb: Callback<MintSpecies>
  ): void;

  once(event: "SetBreedingRules", cb: Callback<SetBreedingRules>): void;
  once(
    event: "SetBreedingRules",
    options: EventOptions,
    cb: Callback<SetBreedingRules>
  ): void;
}
