/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type SetAllowedRoot = ContractEventLog<{
  minterContract: string;
  speciesId: string;
  merkleRoot: string;
  0: string;
  1: string;
  2: string;
}>;

export interface MintGuardMerkle extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): MintGuardMerkle;
  clone(): MintGuardMerkle;
  methods: {
    addAllowedRoot(
      minterContract: string,
      speciesId: number | string | BN,
      merkleRoot: string | number[]
    ): NonPayableTransactionObject<void>;

    allowMint(
      speciesId: number | string | BN,
      user: string,
      merkleRoot: string | number[],
      merkleProof: (string | number[])[]
    ): NonPayableTransactionObject<boolean>;

    removeAllowedRoot(
      minterContract: string,
      speciesId: number | string | BN,
      merkleRoot: string | number[]
    ): NonPayableTransactionObject<void>;

    supportsInterface(
      interfaceId: string | number[]
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    SetAllowedRoot(cb?: Callback<SetAllowedRoot>): EventEmitter;
    SetAllowedRoot(
      options?: EventOptions,
      cb?: Callback<SetAllowedRoot>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "SetAllowedRoot", cb: Callback<SetAllowedRoot>): void;
  once(
    event: "SetAllowedRoot",
    options: EventOptions,
    cb: Callback<SetAllowedRoot>
  ): void;
}
