/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type NewClone = ContractEventLog<{
  instance: string;
  implementation: string;
  salt: string;
  0: string;
  1: string;
  2: string;
}>;

export interface OZClonesFactory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): OZClonesFactory;
  clone(): OZClonesFactory;
  methods: {
    clone(
      implementation: string,
      data: string | number[]
    ): NonPayableTransactionObject<string>;

    cloneDeterministic(
      implementation: string,
      salt: string | number[],
      data: string | number[]
    ): NonPayableTransactionObject<string>;

    predictDeterministicAddress(
      implementation: string,
      salt: string | number[]
    ): NonPayableTransactionObject<string>;
  };
  events: {
    NewClone(cb?: Callback<NewClone>): EventEmitter;
    NewClone(options?: EventOptions, cb?: Callback<NewClone>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "NewClone", cb: Callback<NewClone>): void;
  once(event: "NewClone", options: EventOptions, cb: Callback<NewClone>): void;
}
