/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { CrafterContract as ContractInterface } from '../../typechain/Crafter';
import Artifact from '../../artifacts/contracts/Crafter/Crafter.sol/Crafter.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;