/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ERC1820RegistryContract as ContractInterface } from '../../typechain/ERC1820Registry';
import Artifact from '../../artifacts/contracts/ERC1820/ERC1820Registry.sol/ERC1820Registry.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;