/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ERC1820ImplementerAuthorizeAllContract as ContractInterface } from '../../typechain/ERC1820ImplementerAuthorizeAll';
import Artifact from '../../artifacts/contracts/ERC1820/ERC1820ImplementerAuthorizeAll.sol/ERC1820ImplementerAuthorizeAll.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;