/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ERC721MintableContract as ContractInterface } from '../../typechain/ERC721Mintable';
import Artifact from '../../artifacts/contracts/ERC721/ERC721Mintable.sol/ERC721Mintable.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;