/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { FactoryERC20Contract as ContractInterface } from '../../typechain/FactoryERC20';
import Artifact from '../../artifacts/contracts/Testing/FactoryERC20.sol/FactoryERC20.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;