/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { FactoryERC721Contract as ContractInterface } from '../../typechain/FactoryERC721';
import Artifact from '../../artifacts/contracts/Testing/FactoryERC721.sol/FactoryERC721.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;