/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { InterfaceIdsContract as ContractInterface } from '../../typechain/InterfaceIds';
import Artifact from '../../artifacts/contracts/Testing/InterfaceIds.sol/InterfaceIds.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;