/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MintGuardLimitedMintsContract as ContractInterface } from '../../typechain/MintGuardLimitedMints';
import Artifact from '../../artifacts/contracts/Minter/modules/MintGuard/builds/MintGuardLimitedMints.sol/MintGuardLimitedMints.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;