/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MinterSimpleContract as ContractInterface } from '../../typechain/MinterSimple';
import Artifact from '../../artifacts/contracts/Minter/builds/MinterSimple.sol/MinterSimple.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;