/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MinterSimpleMerkleContract as ContractInterface } from '../../typechain/MinterSimpleMerkle';
import Artifact from '../../artifacts/contracts/Minter/builds/MinterSimpleMerkle.sol/MinterSimpleMerkle.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;