/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MintGuardAllowlistContract as ContractInterface } from '../../typechain/MintGuardAllowlist';
import Artifact from '../../artifacts/contracts/Minter/modules/MintGuard/builds/MintGuardAllowlist.sol/MintGuardAllowlist.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;