/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MinterBreedingContract as ContractInterface } from '../../typechain/MinterBreeding';
import Artifact from '../../artifacts/contracts/Minter/builds/MinterBreeding.sol/MinterBreeding.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;