/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MintGuardMerkleContract as ContractInterface } from '../../typechain/MintGuardMerkle';
import Artifact from '../../artifacts/contracts/Minter/modules/MintGuard/builds/MintGuardMerkle.sol/MintGuardMerkle.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;