/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MinterRandomContract as ContractInterface } from '../../typechain/MinterRandom';
import Artifact from '../../artifacts/contracts/Minter/builds/MinterRandom.sol/MinterRandom.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;