/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MinterCoreFactoryContract as ContractInterface } from '../../typechain/MinterCoreFactory';
import Artifact from '../../artifacts/contracts/Minter/MinterCoreFactory.sol/MinterCoreFactory.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;