/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MinterAutoIdContract as ContractInterface } from '../../typechain/MinterAutoId';
import Artifact from '../../artifacts/contracts/Minter/builds/MinterAutoId.sol/MinterAutoId.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;