/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { RosalindTestLabContract as ContractInterface } from '../../typechain/RosalindTestLab';
import Artifact from '../../artifacts/contracts/Testing/RosalindTestLab.sol/RosalindTestLab.json';

const Contract = require('@truffle/contract');
export default Contract(Artifact) as ContractInterface;