/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractFactory } from 'ethers';
import { abi, bytecode } from '../../artifacts/contracts/Crafter/CrafterMint.sol/CrafterMint.json';

export default new ContractFactory(abi, bytecode);