/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractFactory } from 'ethers';
import { abi, bytecode } from '../../artifacts/contracts/Utils/Create2CloneFactory.sol/Create2CloneFactory.json';

export default new ContractFactory(abi, bytecode);