/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractFactory } from 'ethers';
import { abi, bytecode } from '../../artifacts/contracts/ERC1820/ERC1820Registry.sol/ERC1820Registry.json';

export default new ContractFactory(abi, bytecode);