/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractFactory } from 'ethers';
import { abi, bytecode } from '../../artifacts/contracts/ERC721/ERC721MintableCode.sol/ERC721MintableCode.json';

export default new ContractFactory(abi, bytecode);