/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractFactory } from 'ethers';
import { abi, bytecode } from '../../artifacts/contracts/Testing/FactoryERC721.sol/FactoryERC721.json';

export default new ContractFactory(abi, bytecode);