/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractFactory } from 'ethers';
import { abi, bytecode } from '../../artifacts/contracts/Testing/InterfaceIds.sol/InterfaceIds.json';

export default new ContractFactory(abi, bytecode);