/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractFactory } from 'ethers';
import { abi, bytecode } from '../../artifacts/contracts/Minter/builds/MinterBreeding.sol/MinterBreeding.json';

export default new ContractFactory(abi, bytecode);