/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractFactory } from 'ethers';
import { abi, bytecode } from '../../artifacts/contracts/Minter/modules/MintGuard/builds/MintGuardLimitedMints.sol/MintGuardLimitedMints.json';

export default new ContractFactory(abi, bytecode);