/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ERC20Mint, ERC20MintInterface } from "../ERC20Mint";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ERC20Mint__factory {
  static readonly abi = _abi;
  static createInterface(): ERC20MintInterface {
    return new utils.Interface(_abi) as ERC20MintInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC20Mint {
    return new Contract(address, _abi, signerOrProvider) as ERC20Mint;
  }
}
