/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ERC721Mint, ERC721MintInterface } from "../ERC721Mint";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ERC721Mint__factory {
  static readonly abi = _abi;
  static createInterface(): ERC721MintInterface {
    return new utils.Interface(_abi) as ERC721MintInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC721Mint {
    return new Contract(address, _abi, signerOrProvider) as ERC721Mint;
  }
}
