/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { InterfaceIds, InterfaceIdsInterface } from "../InterfaceIds";

const _abi = [
  {
    inputs: [],
    name: "minterAutoIdInterfaceId",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "minterBreedingInterfaceId",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "minterCoreInterfaceId",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "minterRandomInterfaceId",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "minterSimpleInterfaceId",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610246806100206000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c80630da8bb1f1461005c57806342959b7e1461007a5780635a427f53146100985780636dc9c11e146100b6578063b5707170146100d4575b600080fd5b6100646100f2565b60405161007191906101f5565b60405180910390f35b61008261011a565b60405161008f91906101f5565b60405180910390f35b6100a0610142565b6040516100ad91906101f5565b60405180910390f35b6100be61016a565b6040516100cb91906101f5565b60405180910390f35b6100dc610192565b6040516100e991906101f5565b60405180910390f35b60007ff5b8312700000000000000000000000000000000000000000000000000000000905090565b60007f9ec8dc4000000000000000000000000000000000000000000000000000000000905090565b60007f91b9498000000000000000000000000000000000000000000000000000000000905090565b60007f1f3a5ae100000000000000000000000000000000000000000000000000000000905090565b60007fdbe00cca00000000000000000000000000000000000000000000000000000000905090565b60007fffffffff0000000000000000000000000000000000000000000000000000000082169050919050565b6101ef816101ba565b82525050565b600060208201905061020a60008301846101e6565b9291505056fea264697066735822122081cb8468983b0eaa3ad6baa75f3c9551075ab5b64d6e20c005484b8f23f01c0164736f6c63430008090033";

export class InterfaceIds__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<InterfaceIds> {
    return super.deploy(overrides || {}) as Promise<InterfaceIds>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): InterfaceIds {
    return super.attach(address) as InterfaceIds;
  }
  connect(signer: Signer): InterfaceIds__factory {
    return super.connect(signer) as InterfaceIds__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): InterfaceIdsInterface {
    return new utils.Interface(_abi) as InterfaceIdsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InterfaceIds {
    return new Contract(address, _abi, signerOrProvider) as InterfaceIds;
  }
}
