name: Default Actions

on:
  push:
    branches:
      - master
      - develop
  pull_request: ~

env:
  PRIV_KEY: ${{ secrets.PRIV_KEY }}
  PROXY_PRIV_KEY: ${{ secrets.PROXY_PRIV_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MOONBEAM_API_KEY: ${{ secrets.MOONBEAM_API_KEY }}
  MOONRIVER_API_KEY: ${{ secrets.MOONRIVER_API_KEY }}
  AURORA_API_KEY: ${{ secrets.AURORA_API_KEY }}
  FANTOM_API_KEY: ${{ secrets.FANTOM_API_KEY }}
  AVAX_API_KEY: ${{ secrets.AVAX_API_KEY }}
  OPTIMISM_API_KEY: ${{ secrets.OPTIMISM_API_KEY }}
  ARBITRUM_API_KEY: ${{ secrets.ARBITRUM_API_KEY }}
  BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
  POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
  MAINNET_API_KEY: ${{ secrets.MAINNET_API_KEY }}
  OTHER_PRIV_KEY: ${{ secrets.OTHER_PRIV_KEY }}

jobs:
  run-coverage:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.16"
      # PNPM Cache
      - run: npm i --global pnpm
      - name: Cache pnpm store
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store/
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      # Set login for package registries
      - run: npm set //registry.npmjs.org/:_authToken=${{secrets.NPMJS_TOKEN}}
      - run: npm set //npm.pkg.github.com/:_authToken=${{secrets.GPR_TOKEN}}
      # Install
      - run: pnpm i
      - run: pnpm run coverage
  # run-tests:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: "16.16"
  #     # PNPM Cache
  #     - run: npm i --global pnpm
  #     - name: Cache pnpm store
  #       uses: actions/cache@v2
  #       env:
  #         cache-name: cache-pnpm-store
  #       with:
  #         path: ~/.pnpm-store/
  #         key: ${{ runner.os }}-build-${{ env.cache-name }}
  #     # Set login for package registries
  #     - run: npm set //registry.npmjs.org/:_authToken=${{secrets.NPMJS_TOKEN}}
  #     - run: npm set //npm.pkg.github.com/:_authToken=${{secrets.GPR_TOKEN}}
  #     # Install
  #     - run: pnpm i
  #     - run: pnpm run build
  #     - run: npm run test
