name: Default Actions

on:
  push:
    branches:
      - master
      - develop
  pull_request: ~

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.19"
      # PNPM Cache
      - run: npm i --global pnpm
      - name: Cache pnpm store
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store/
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      # Set login for package registries
      - run: npm set //registry.npmjs.org/:_authToken=${{secrets.NPMJS_TOKEN}}
      - run: npm set //npm.pkg.github.com/:_authToken=${{secrets.GPR_TOKEN}}
      # Install
      - run: pnpm i
      - run: pnpm run build
      - name: build files
        env: 
          PRIV_KEY: f40d99a142302f3ee15ba30339fb30dd0e5073dfa49f449f02982e68915562fa
          PROXY_PRIV_KEY: 4688f661095f699be837a99b5c857a99b51a8659ee87b3f9a1f04d244df763ba

      - run: npm run test
